## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np

# Import API key
from config_1 import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3hrs),Snow inches (last 3hrs)
0,0,Faanui,PF,2022-07-16 02:16:05,-16.4833,-151.7500,76.41,71,10,23.67,light rain,0.0,0.0
1,1,Nishihara,JP,2022-07-16 02:16:05,26.1842,127.7558,87.85,81,100,12.66,overcast clouds,0.0,0.0
2,2,Albany,US,2022-07-16 02:16:05,42.6001,-73.9662,70.45,70,64,2.86,broken clouds,0.0,0.0
3,3,Cape Town,ZA,2022-07-16 02:16:06,-33.9258,18.4232,59.38,84,39,3.44,fog,0.0,0.0
4,4,Antofagasta,CL,2022-07-16 02:16:06,-23.6500,-70.4000,54.68,81,1,5.73,clear sky,0.0,0.0

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is your desired minimum temperature for your trip? "))
max_temp = float(input("What is your desired maximum temperature for your trip? "))

What is your desired minimum temperature for your trip? 40
What is your desired maximum temperature for your trip? 90

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] >= min_temp) &
                                       (city_data_df["Max Temp"] <= max_temp)]
preferred_cities_df

,City ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3hrs),Snow inches (last 3hrs)
0,0,Faanui,PF,2022-07-16 02:16:05,-16.4833,-151.7500,76.41,71,10,23.67,light rain,0.0,0.0
1,1,Nishihara,JP,2022-07-16 02:16:05,26.1842,127.7558,87.85,81,100,12.66,overcast clouds,0.0,0.0
2,2,Albany,US,2022-07-16 02:16:05,42.6001,-73.9662,70.45,70,64,2.86,broken clouds,0.0,0.0
3,3,Cape Town,ZA,2022-07-16 02:16:06,-33.9258,18.4232,59.38,84,39,3.44,fog,0.0,0.0
4,4,Antofagasta,CL,2022-07-16 02:16:06,-23.6500,-70.4000,54.68,81,1,5.73,clear sky,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
559,559,Villarrica,PY,2022-07-16 02:18:43,-25.7500,-56.4333,77.94,57,100,8.01,light rain,0.0,0.0
560,560,Kerema,PG,2022-07-16 02:18:43,-7.9631,145.7785,78.55,70,100,6.08,overcast clouds,0.0,0.0
561,561,Lloydminster,CA,2022-07-16 02:15:52,53.2835,-110.0016,79.02,69,20,10.36,few clouds,0.0,0.0
562,562,Accra,GH,2022-07-16 02:13:47,5.5560,-0.1969,75.07,89,100,10.47,light rain,0.0,0.0
563,563,Avera,US,2022-07-16 02:18:44,33.1940,-82.5271,77.05,69,86,5.88,overcast clouds,0.0,0.0

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.isnull().sum()

City ID                    0
City                       0
Country                    4
Date                       0
Lat                        0
Lng                        0
Max Temp                   0
Humidity                   0
Cloudiness                 0
Wind Speed                 0
Current Description        0
Rain inches (last 3hrs)    0
Snow inches (last 3hrs)    0
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna()
clean_df.count()

City ID                    531
City                       531
Country                    531
Date                       531
Lat                        531
Lng                        531
Max Temp                   531
Humidity                   531
Cloudiness                 531
Wind Speed                 531
Current Description        531
Rain inches (last 3hrs)    531
Snow inches (last 3hrs)    531
dtype: int64

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Faanui,PF,76.41,light rain,-16.4833,-151.7500,
1,Nishihara,JP,87.85,overcast clouds,26.1842,127.7558,
2,Albany,US,70.45,broken clouds,42.6001,-73.9662,
3,Cape Town,ZA,59.38,fog,-33.9258,18.4232,
4,Antofagasta,CL,54.68,clear sky,-23.6500,-70.4000,
5,Mataura,NZ,43.72,broken clouds,-46.1927,168.8643,
6,Itaobim,BR,64.65,overcast clouds,-16.5667,-41.8333,
7,Teguise,ES,68.22,clear sky,29.0605,-13.5640,
8,Kajaani,FI,55.45,clear sky,64.2273,27.7285,
9,Severo-Kurilsk,RU,56.91,overcast clouds,50.6789,156.1250,

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
   
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
        
    except (IndexError):
        print("Cannot find hotel...skipping.")

Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.
Cannot find hotel...skipping.

In [9]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df["Hotel Name"].replace('',np.nan,inplace=True)
hotel_df.dropna(subset=["Hotel Name"], inplace=True)

In [10]:
#Create a new dataframe to store the location,weather data and nearest hotel.
clean_hotel_df = hotel_df
clean_hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Faanui,PF,76.41,light rain,-16.4833,-151.7500,Bora-Bora Pearl Beach Resort & Spa
3,Cape Town,ZA,59.38,fog,-33.9258,18.4232,"Radisson Blu Hotel Waterfront, Cape Town"
4,Antofagasta,CL,54.68,clear sky,-23.6500,-70.4000,"Holiday Inn Express Antofagasta, an IHG Hotel"
5,Mataura,NZ,43.72,broken clouds,-46.1927,168.8643,Ellie's Villa
7,Teguise,ES,68.22,clear sky,29.0605,-13.5640,B&B La Casona de Nazaret
9,Severo-Kurilsk,RU,56.91,overcast clouds,50.6789,156.1250,Kak Doma
10,Hobart,AU,52.27,light rain,-42.8794,147.3294,St Ives Hobart Accommodation Tasmania
11,Hermanus,ZA,52.81,broken clouds,-34.4187,19.2345,Misty Waves Boutique Hotel
12,Touros,BR,73.89,clear sky,-5.1989,-35.4608,INN NEW HORIZON
13,Puerto Ayora,EC,69.55,overcast clouds,-0.7393,-90.3518,Finch Bay Galapagos Hotel

In [11]:
# 8a. Create the output File (CSV)
output_data_file = "weatherpy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [12]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [14]:
# 11a. Add a marker layer for each city to the map. 

max_temp = clean_hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))